### PR TITLE
Adjusted Dracula Theme

### PR DESCRIPTION
**Pull request by WillMexe**
I adjusted the colors a bit as i thought some looked off. In my opinion some of them looked off so i adjusted them to where i think they look better together. For example the white looked a little to dark which made it seem like a murky gray and the black was darker than its bright equivalent also most of the colors are the same which looked weird in my setup. Any feedback is appreciated this is just some edits i thought looked better.

### CODE REVIEW

**Comment by lemnos** [comment]
Thanks :). Unfortunately it looks like the patch you sent is  wrong. The commit only appears to add a single newline.

**Comment by WillMexe** [comment]
Sorry for the late reply i was not at home. I will check this out as i am pretty sure more  than 1 lines should have been affected.

**Comment by WillMexe** [comment]
I think  that should have done it. There seems to have been a error last time.

**Comment by lemnos** [comment]
Looks good.

**Pull request merged**
